In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.stats import genpareto
from scipy.cluster.hierarchy import linkage, fcluster, dendrogram
from scipy.spatial.distance import pdist, squareform
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

DATA = Path("..") / "data"
FIGURAS = Path("..") / "figuras"
FIGURAS.mkdir(exist_ok=True)

# Umbrales del modelo (src/train.py) y periodo de entrenamiento de la red
U = {"O3": 63.0, "SO2": 20.2, "PM2.5": 38.0}
X = {"O3": 27.0, "SO2": 54.8, "PM2.5": 38.0}
INICIO, FIN = "2023-01-01", "2025-01-01"

In [2]:
ni = pd.read_csv(DATA / "datos_no_imputados.csv", low_memory=False)
for c in [c for c in ni.columns if " (" in c]:
    ni[c.split(" (")[0]] = ni[c.split(" (")[0]].fillna(ni[c])
ni["Fecha y hora"] = pd.to_datetime(ni["Fecha y hora"])

# Limpieza básica (Etapa 2)
for v in ["O3", "SO2", "PM2.5", "PM10"]:
    ni.loc[ni[v] < 0, v] = np.nan
ni.loc[ni["PM10"] >= 999, "PM10"] = np.nan
mal = ni["PM2.5"] > ni["PM10"]
ni.loc[mal, ["PM2.5", "PM10"]] = np.nan

obs = ni[(ni["Fecha y hora"] >= INICIO) & (ni["Fecha y hora"] < FIN)]
print(obs.shape)

(263111, 33)

In [ ]:
obs["Fecha y hora"] = pd.to_datetime(obs["Fecha y hora"])
obs["Dia_semana"] = obs["Fecha y hora"].dt.day_of_week
obs["Mes"] = obs["Fecha y hora"].dt.month
obs["Hora"] = obs["Fecha y hora"].dt.hour

In [21]:
obs.head()

,Fecha y hora,CO,NO,NO2,NOX,O3,PM10,PM2.5,PRS,RAINF,...,SO2 (ppb),SR (kW/m2),TOUT (ºC),WSR (km/h),WDR (azimutal),Fecha,Dia,Dia_semana,Hora,Mes
360114,2023-01-01 00:00:00,1.67,4.1,30.3,34.5,9.0,118.0,94.12,718.4,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-01-01,1,6,0,1
360115,2023-01-01 01:00:00,1.70,5.0,28.9,34.1,9.0,97.0,96.79,710.7,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-01-01,1,6,1,1
360116,2023-01-01 02:00:00,1.51,4.3,23.2,27.7,11.0,103.0,81.23,710.4,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-01-01,1,6,2,1
360117,2023-01-01 03:00:00,1.30,3.8,20.9,24.9,11.0,83.0,49.83,710.1,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-01-01,1,6,3,1
360118,2023-01-01 04:00:00,1.28,4.6,20.7,25.5,9.0,65.0,40.19,710.2,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-01-01,1,6,4,1

In [70]:
var = "O3"
d = obs[(obs["TOUT"] > 40) & (obs["Hora"] < 16) & (obs["Hora"] > 12) & (obs["WSR"] < 5)] 
# d = obs
extra = 0
e = d[var][d[var] > U[var]+extra] - (U[var]+extra)
fila = {"excesos": len(e)}
if len(e) >= 30:                       # con menos de 30 excesos el ajuste no es confiable
    xi, _, sigma = genpareto.fit(e, floc=0)
    prob = 1 - genpareto.cdf(x=X[var]-extra, c=xi, scale=sigma)
    fila.update(xi=float(xi), sigma=float(sigma), prob=float(prob))
    
print(fila)

{'excesos': 17}

In [ ]:
features = ["PRS", "RAINF", "RH", "SR", "TOUT", "WSR", "Hora"]# "Mes", "Dia_Sema"
df = obs.copy()
for f in features:
    df[f] = pd.qcut(df[f], q=4, labels=False, duplicates='drop')

In [100]:
from itertools import product

var = "O3"
extra = [0, 10, 20]

# 1. Create Cartesian product grid DataFrame
unique_vals = [df[f].unique() for f in features]
df_new = pd.DataFrame(product(*unique_vals), columns=features)

# Initialize output columns
df_new["prob_0"] = 0.0
df_new["prob_10"] = 0.0
df_new["prob_20"] = 0.0

# 2. Iterate through each combination
for vals in df_new[features].itertuples(index=False):
    # Convert named tuple/row to list matching `vals`
    val_list = list(vals)
    
    # Filter original dataframe for the matching subset
    mask_df = (df[features] == val_list).all(axis=1)
    d = df[mask_df]
    
    # Filter df_new to update the current combination
    mask_df_new = (df_new[features] == val_list).all(axis=1)
    
    for ext in extra:
        
        # Calculate excesses
        threshold = U[var] + ext
        e = d[var][d[var] > threshold] - threshold
        
        if len(e) >= 30:
            xi, _, sigma = genpareto.fit(e, floc=0)
            prob = 1 - genpareto.cdf(x=X[var] - ext, c=xi, scale=sigma)
            
            # Update columns correctly in df_new
            df_new.loc[mask_df_new, f"prob_{ext}"] = prob

df_new.head()

   PRS  RAINF   RH   SR  TOUT  WSR  Hora  prob_0  prob_10  prob_20
0  2.0    0.0  1.0  0.0   0.0  1.0     0     0.0      0.0      0.0
1  2.0    0.0  1.0  0.0   0.0  1.0     1     0.0      0.0      0.0
2  2.0    0.0  1.0  0.0   0.0  1.0     2     0.0      0.0      0.0
3  2.0    0.0  1.0  0.0   0.0  1.0     3     0.0      0.0      0.0
4  2.0    0.0  1.0  0.0   0.0  0.0     0     0.0      0.0      0.0

In [119]:
df_new[df_new["prob_0"] > 0.0].sort_values(by="prob_0", ascending=False)

       PRS  RAINF   RH   SR  TOUT  WSR  Hora    prob_0   prob_10   prob_20
6274   1.0    0.0  0.0  2.0   3.0  3.0     2  0.378675  0.000000  0.000000
11370  0.0    0.0  0.0  3.0   3.0  2.0     2  0.358006  0.494180  0.722571
11362  0.0    0.0  0.0  3.0   3.0  1.0     2  0.337624  0.462718  0.698407
11074  0.0    0.0  0.0  0.0   3.0  3.0     2  0.319315  0.510203  0.798644
10362  0.0    0.0  1.0  3.0   3.0  1.0     2  0.315021  0.479069  0.000000
11274  0.0    0.0  0.0  2.0   3.0  3.0     2  0.313312  0.000000  0.000000
1366   2.0    0.0  0.0  3.0   3.0  0.0     2  0.308010  0.513310  0.691503
11374  0.0    0.0  0.0  3.0   3.0  3.0     2  0.295740  0.430110  0.700795
6271   1.0    0.0  0.0  2.0   3.0  2.0     3  0.290789  0.000000  0.000000
11270  0.0    0.0  0.0  2.0   3.0  2.0     2  0.289904  0.000000  0.000000
10374  0.0    0.0  1.0  3.0   3.0  3.0     2  0.287334  0.419681  0.692057
11070  0.0    0.0  0.0  0.0   3.0  2.0     2  0.282007  0.441358  0.000000
6374   1.0    0.0  0.0  3.0   3.0  3.0     2  0.275869  0.481258  0.756778
10370  0.0    0.0  1.0  3.0   3.0  2.0     2  0.263225  0.427242  0.694256
5374   1.0    0.0  1.0  3.0   3.0  3.0     2  0.262665  0.425528  0.741076
6362   1.0    0.0  0.0  3.0   3.0  1.0     2  0.238686  0.393151  0.653781
11375  0.0    0.0  0.0  3.0   3.0  3.0     3  0.236818  0.000000  0.000000
11054  0.0    0.0  0.0  0.0   2.0  3.0     2  0.236455  0.443957  0.000000
21366  3.0    0.0  0.0  3.0   3.0  0.0     2  0.224715  0.357195  0.000000
11366  0.0    0.0  0.0  3.0   3.0  0.0     2  0.216722  0.000000  0.000000
366    2.0    0.0  1.0  3.0   3.0  0.0     2  0.216242  0.000000  0.000000
1374   2.0    0.0  0.0  3.0   3.0  3.0     2  0.215483  0.362499  0.685907
6370   1.0    0.0  0.0  3.0   3.0  2.0     2  0.214229  0.350107  0.620720
374    2.0    0.0  1.0  3.0   3.0  3.0     2  0.192610  0.332250  0.584721
6366   1.0    0.0  0.0  3.0   3.0  0.0     2  0.183966  0.317944  0.000000
1370   2.0    0.0  0.0  3.0   3.0  2.0     2  0.176166  0.367056  0.648381
1362   2.0    0.0  0.0  3.0   3.0  1.0     2  0.175581  0.297090  0.000000
20366  3.0    0.0  1.0  3.0   3.0  0.0     2  0.170042  0.000000  0.000000
370    2.0    0.0  1.0  3.0   3.0  2.0     2  0.169097  0.340947  0.000000
10074  0.0    0.0  1.0  0.0   3.0  3.0     2  0.167269  0.275249  0.570522
21362  3.0    0.0  0.0  3.0   3.0  1.0     2  0.158878  0.338163  0.676024
11271  0.0    0.0  0.0  2.0   3.0  2.0     3  0.154144  0.389772  0.000000
11075  0.0    0.0  0.0  0.0   3.0  3.0     3  0.150459  0.000000  0.000000
6275   1.0    0.0  0.0  2.0   3.0  3.0     3  0.137121  0.323763  0.000000
5362   1.0    0.0  1.0  3.0   3.0  1.0     2  0.134256  0.266442  0.000000
11354  0.0    0.0  0.0  3.0   2.0  3.0     2  0.131851  0.377464  0.000000
20362  3.0    0.0  1.0  3.0   3.0  1.0     2  0.126673  0.000000  0.000000
6354   1.0    0.0  0.0  3.0   2.0  3.0     2  0.121745  0.313976  0.000000
362    2.0    0.0  1.0  3.0   3.0  1.0     2  0.117722  0.000000  0.000000
21370  3.0    0.0  0.0  3.0   3.0  2.0     2  0.113507  0.280502  0.732607
20370  3.0    0.0  1.0  3.0   3.0  2.0     2  0.111029  0.000000  0.000000
5354   1.0    0.0  1.0  3.0   2.0  3.0     2  0.105946  0.203102  0.000000
5370   1.0    0.0  1.0  3.0   3.0  2.0     2  0.103350  0.219571  0.000000
11275  0.0    0.0  0.0  2.0   3.0  3.0     3  0.100378  0.213154  0.000000
6070   1.0    0.0  0.0  0.0   3.0  2.0     2  0.093963  0.000000  0.000000
10354  0.0    0.0  1.0  3.0   2.0  3.0     2  0.089669  0.174169  0.000000
21374  3.0    0.0  0.0  3.0   3.0  3.0     2  0.084789  0.298640  0.000000
11342  0.0    0.0  0.0  3.0   2.0  1.0     2  0.072779  0.000000  0.000000
11350  0.0    0.0  0.0  3.0   2.0  2.0     2  0.071707  0.206975  0.000000
20374  3.0    0.0  1.0  3.0   3.0  3.0     2  0.065420  0.000000  0.000000
5350   1.0    0.0  1.0  3.0   2.0  2.0     2  0.061855  0.000000  0.000000
1354   2.0    0.0  0.0  3.0   2.0  3.0     2  0.061417  0.000000  0.000000
1350   2.0    0.0  0.0  3.0   2.0  2.0     2  0.051890  0.000000  0.000000
1275   2.0    0.0  0.0  2.0   3.0  3.0     3  0.051730  0.000000  0.000000
6350   1.0    0.0  0.0  3.0   2.0  2.0     2  0.048938  0.111482  0.000000
6342   1.0    0.0  0.0  3.0   2.0  1.0     2  0.040624  0.000000  0.000000
21350  3.0    0.0  0.0  3.0   2.0  2.0     2  0.018404  0.000000  0.000000
10350  0.0    0.0  1.0  3.0   2.0  2.0     2  0.000668  0.000000  0.000000

In [120]:
(df[  (df["PRS"]  ==  1)
   & (df["RAINF"] ==  0)
   & (df["RH"]    ==  0)
   & (df["SR"]    ==  2)
   & (df["TOUT"]  ==  3)
   & (df["WSR"]   ==  3)
   & (df["Hora"]  ==  2)
   & (df["O3"]    >  90.0)]["O3"].count() /
df[  (df["PRS"]   ==  1)
   & (df["RAINF"] ==  0)
   & (df["RH"]    ==  0)
   & (df["SR"]    ==  2)
   & (df["TOUT"]  ==  3)
   & (df["WSR"]   ==  3)
   & (df["Hora"]  ==  2)
   & (df["O3"]    >  63.0)]["O3"].count())

np.float64(0.25)

In [121]:
df[  (df["PRS"]   ==  1)
   & (df["RAINF"] ==  0)
   & (df["RH"]    ==  0)
   & (df["SR"]    ==  2)
   & (df["TOUT"]  ==  3)
   & (df["WSR"]   ==  3)
   & (df["Hora"]  ==  2)
   & (df["O3"]    >  63.0)]

,Fecha y hora,CO,NO,NO2,NOX,O3,PM10,PM2.5,PRS,RAINF,...,SO2 (ppb),SR (kW/m2),TOUT (ºC),WSR (km/h),WDR (azimutal),Fecha,Dia,Dia_semana,Hora,Mes
367138,2023-10-20 17:00:00,1.00,3.3,21.5,24.8,113.0,75.0,24.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-10-20,20,4,2,10
370280,2023-02-28 17:00:00,1.12,4.4,16.0,20.4,82.0,142.0,24.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-02-28,28,1,2,2
370304,2023-03-01 17:00:00,1.10,5.7,15.5,21.2,66.0,111.0,20.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-03-01,1,2,2,3
370544,2023-03-11 17:00:00,1.28,5.6,15.6,21.1,66.0,118.0,34.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-03-11,11,5,2,3
370904,2023-03-26 17:00:00,1.15,4.6,15.4,20.0,72.0,91.0,27.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-03-26,26,6,2,3
377647,2023-01-01 17:00:00,1.29,4.8,24.3,29.1,69.0,54.0,12.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-01-01,1,6,2,1
385109,2023-11-08 17:00:00,2.15,8.4,46.6,55.0,78.0,137.0,59.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-11-08,8,2,2,11
475641,2023-03-11 17:00:00,1.61,3.7,11.9,15.6,71.0,92.0,31.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-03-11,11,5,2,3
476001,2023-03-26 17:00:00,1.60,3.4,12.4,15.8,77.0,79.0,24.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-03-26,26,6,2,3
476984,2023-05-06 16:00:00,0.84,2.8,20.9,23.8,88.0,106.0,55.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-05-06,6,5,2,5
477945,2023-06-15 17:00:00,0.86,3.0,22.0,25.1,94.0,119.0,37.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-06-15,15,3,2,6
480969,2023-10-19 17:00:00,0.91,4.6,22.2,26.8,67.0,51.0,13.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-10-19,19,3,2,10
480993,2023-10-20 17:00:00,1.05,3.9,28.5,32.4,118.0,86.0,19.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-10-20,20,4,2,10
481017,2023-10-21 17:00:00,0.66,2.9,9.3,12.2,65.0,52.0,14.00,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2023-10-21,21,5,2,10
494572,2024-05-08 16:00:00,3.28,2.5,10.4,12.8,89.0,159.0,NaN,1.0,0.0,...,2.9,0.139,36.88,23.0,109.0,2024-05-08,8,2,2,5
494573,2024-05-08 17:00:00,3.24,2.7,9.1,11.8,79.0,124.0,NaN,1.0,0.0,...,3.0,0.226,36.81,20.0,109.0,2024-05-08,8,2,2,5
494764,2024-05-16 16:00:00,3.49,3.2,11.8,15.0,86.0,NaN,NaN,1.0,0.0,...,3.3,0.218,35.56,17.0,113.0,2024-05-16,16,3,2,5
506789,2024-09-28 17:00:00,0.78,2.3,10.3,12.8,74.0,48.0,14.56,1.0,0.0,...,3.9,0.187,29.41,12.0,78.0,2024-09-28,28,5,2,9
544967,2024-02-02 17:00:00,2.75,4.4,14.6,19.0,66.0,122.0,17.00,1.0,0.0,...,5.2,0.163,28.81,13.8,139.0,2024-02-02,2,4,2,2
545951,2024-03-14 17:00:00,3.25,4.1,17.0,21.1,77.0,72.0,16.00,1.0,0.0,...,4.5,0.070,30.72,13.3,159.0,2024-03-14,14,3,2,3
589600,2024-03-03 17:00:00,4.52,3.8,17.9,21.6,110.0,84.0,32.00,1.0,0.0,...,7.0,0.224,29.24,13.0,150.0,2024-03-03,3,6,2,3
589696,2024-03-07 17:00:00,5.13,3.6,27.3,31.0,116.0,61.0,41.00,1.0,0.0,...,4.6,0.174,29.05,13.7,148.0,2024-03-07,7,3,2,3
589840,2024-03-13 17:00:00,4.80,3.9,11.0,14.9,93.0,76.0,7.00,1.0,0.0,...,3.8,0.225,32.37,13.1,180.0,2024-03-13,13,2,2,3
589863,2024-03-14 16:00:00,2.67,5.5,29.4,34.9,86.0,75.0,21.00,1.0,0.0,...,3.7,0.221,32.64,13.2,141.0,2024-03-14,14,3,2,3
590632,2024-04-15 17:00:00,2.50,3.5,27.0,30.6,113.0,113.0,42.00,1.0,0.0,...,3.4,0.219,31.76,13.7,206.0,2024-04-15,15,0,2,4
591589,2024-05-25 16:00:00,2.64,1.9,8.8,10.7,85.0,103.0,55.00,1.0,0.0,...,3.6,0.212,37.39,12.8,213.0,2024-05-25,25,5,2,5
591827,2024-06-04 14:00:00,2.98,1.9,25.6,27.5,102.0,105.0,39.00,1.0,0.0,...,3.7,0.190,35.08,13.2,220.0,2024-06-04,4,1,2,6
591949,2024-06-09 16:00:00,2.44,1.1,6.2,7.4,86.0,64.0,33.00,1.0,0.0,...,3.3,0.204,33.27,14.4,208.0,2024-06-09,9,6,2,6
594590,2024-09-27 17:00:00,0.60,4.7,29.9,34.6,90.0,64.0,18.00,1.0,0.0,...,3.4,0.206,29.07,11.3,187.0,2024-09-27,27,4,2,9
603396,2024-09-28 17:00:00,0.89,2.5,11.9,14.3,74.0,53.0,19.00,1.0,0.0,...,11.4,0.173,30.18,12.1,122.0,2024-09-28,28,5,2,9
603492,2024-10-02 17:00:00,0.82,NaN,7.7,10.2,66.0,48.0,19.00,1.0,0.0,...,8.3,0.231,30.14,12.9,130.0,2024-10-02,2,2,2,10
603660,2024-10-09 17:00:00,0.93,2.5,11.8,14.3,87.0,50.0,NaN,1.0,0.0,...,10.5,0.227,30.65,11.7,132.0,2024-10-09,9,2,2,10